~/workspace$ python3 test.py
Traceback (most recent call last):
  File "/home/runner/workspace/test.py", line 10, in <module>
    asyncio.run(main())
  File "/nix/store/jyvjawqnhnqhwrsinpvx1av7q2p2fcym-python3-3.10.18/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/jyvjawqnhnqhwrsinpvx1av7q2p2fcym-python3-3.10.18/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/workspace/test.py", line 7, in main
    decoded = parser.decode(DATA)
  File "/home/runner/workspace/modules/parser.py", line 54, in decode
    return [ensure_all_decoded(i) for i in raw_decode(b64decode(item_bytes))]
  File "/home/runner/workspace/modules/parser.py", line 26, in raw_decode
    parsed_data: dict[str, list[dict[str, Any]]] = nbt_to_dict(nbt.NBTFile(fileobj=fileobj)) # type: ignore [assignment]
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/nbt/nbt.py", line 641, in __init__
    self.parse_file()
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/nbt/nbt.py", line 670, in parse_file
    self._parse_buffer(self.file)
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/nbt/nbt.py", line 506, in _parse_buffer
    tag._parse_buffer(buffer)
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/nbt/nbt.py", line 414, in _parse_buffer
    self.tags.append(TAGLIST[self.tagID](buffer=buffer))
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/nbt/nbt.py", line 489, in __init__
    self._parse_buffer(buffer)
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/nbt/nbt.py", line 506, in _parse_buffer
    tag._parse_buffer(buffer)
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/nbt/nbt.py", line 506, in _parse_buffer
    tag._parse_buffer(buffer)
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/nbt/nbt.py", line 506, in _parse_buffer
    tag._parse_buffer(buffer)
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/nbt/nbt.py", line 414, in _parse_buffer
    self.tags.append(TAGLIST[self.tagID](buffer=buffer))
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/nbt/nbt.py", line 355, in __init__
    self._parse_buffer(buffer)
  File "/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/nbt/nbt.py", line 363, in _parse_buffer
    self.value = read.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 30: invalid continuation byte